const MIN_PASSWORD_LENGTH = 8
const MAX_PASSWORD_LENGTH = 50

const PASSWORD_MISMATCH = 'Password do not match.'

export const CONSTANTS = {
  MIN_PASSWORD_LENGTH,
  MAX_PASSWORD_LENGTH,

  PASSWORD_MISMATCH,
}
